hint "Beginning JIP Task Manager Test Script. ";
sleep 2;
MissionStatus = "M0";
hint format ["Mission Status is %1", MissionStatus];
sleep 1;  
ExecVM "Scripts\JIPhandle.sqf";
sleep 3; 
hint "Next Case";
sleep 2;
MissionStatus = "M1";
hint format ["Mission Status is %1", MissionStatus];
sleep 1;  
ExecVM "Scripts\JIPhandle.sqf";
sleep 3; 
hint "Next Case";
sleep 2;
MissionStatus = "M2";
hint format ["Mission Status is %1", MissionStatus];
sleep 1;  
ExecVM "Scripts\JIPhandle.sqf";
sleep 3; 
hint "Next Case";
sleep 2;
MissionStatus = "M3";
hint format ["Mission Status is %1", MissionStatus];
sleep 1;  
ExecVM "Scripts\JIPhandle.sqf";
sleep 3; 
hint "Next Case"; 
sleep 2;
MissionStatus = "M4";
hint format ["Mission Status is %1", MissionStatus];
sleep 1;  
ExecVM "Scripts\JIPhandle.sqf";
sleep 3; 
hint "Next Case";
sleep 2;
MissionStatus = "M5";
hint format ["Mission Status is %1", MissionStatus];
sleep 1;  
ExecVM "Scripts\JIPhandle.sqf";
sleep 3; 
hint "Next Case";
sleep 2;
MissionStatus = "M6";
hint format ["Mission Status is %1", MissionStatus];
sleep 1;  
ExecVM "Scripts\JIPhandle.sqf";
sleep 3; 
hint "Next Case";
sleep 2;
MissionStatus = "M7";
hint format ["Mission Status is %1", MissionStatus];
sleep 1;  
ExecVM "Scripts\JIPhandle.sqf";
sleep 3; 
hint "Next Case";
sleep 2;
MissionStatus = "M8";
hint format ["Mission Status is %1", MissionStatus];
sleep 1;  
ExecVM "Scripts\JIPhandle.sqf";
sleep 3; 
hint "Next Case";
sleep 2;
MissionStatus = "M9";
hint format ["Mission Status is %1", MissionStatus];
sleep 1;  
ExecVM "Scripts\JIPhandle.sqf";
sleep 3; 
hint "Next Case";
sleep 2;
MissionStatus = "M10";
hint format ["Mission Status is %1", MissionStatus];
sleep 1;  
ExecVM "Scripts\JIPhandle.sqf";
sleep 3; 
hint "Next Case";
sleep 2;
MissionStatus = "M11";
hint format ["Mission Status is %1", MissionStatus];
sleep 1;  
ExecVM "Scripts\JIPhandle.sqf";
sleep 3; 
hint "Next Case";
sleep 2;
MissionStatus = "M12";
hint format ["Mission Status is %1", MissionStatus];
sleep 1;  
ExecVM "Scripts\JIPhandle.sqf";
sleep 3; 
hint "Next Case";
sleep 2;
MissionStatus = "M13";
hint format ["Mission Status is %1", MissionStatus];
sleep 1;  
ExecVM "Scripts\JIPhandle.sqf";
sleep 3; 
hint "Next Case";
sleep 2;
MissionStatus = "M14";
hint format ["Mission Status is %1", MissionStatus];
sleep 1;  
ExecVM "Scripts\JIPhandle.sqf";
sleep 3; 
hint "Next Case";
sleep 2;
MissionStatus = "DEFAULT";
hint format ["Mission Status is %1", MissionStatus];
sleep 1;  
ExecVM "Scripts\JIPhandle.sqf";
sleep 3; 
hint "End Test";